# Generated by Django 3.0.8 on 2020-08-02 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardmaker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stratagemcard',
            name='art',
            field=models.ImageField(blank=True, null=True, upload_to='art'),
        ),
        migrations.AddField(
            model_name='stratagemcard',
            name='image',
            field=models.ImageField(editable=False, null=True, upload_to='cards'),
        ),
    ]
